// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tekpro.Data;

#nullable disable

namespace Tekpro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016083912_AddSportTable")]
    partial class AddSportTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tekpro.Models.Diary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the content of my first diary entry.",
                            Created = new DateTime(2025, 10, 13, 17, 45, 42, 0, DateTimeKind.Unspecified),
                            Title = "First Diary Entry"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is the content of my second diary entry.",
                            Created = new DateTime(2025, 10, 13, 17, 45, 42, 0, DateTimeKind.Unspecified),
                            Title = "Second Diary Entry"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is the content of my third diary entry.",
                            Created = new DateTime(2025, 10, 13, 17, 45, 42, 0, DateTimeKind.Unspecified),
                            Title = "Third Diary Entry"
                        });
                });

            modelBuilder.Entity("Tekpro.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinuteOfGame")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TeamSport")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sports");
                });
#pragma warning restore 612, 618
        }
    }
}
